amqp:
    server: localhost
    user: mailer
    password: mailer
    email_queue: MAILER_EMAIL
spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: <UNAME>
        password: <PWD>
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

