//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.25 at 04:34:25 PM MSK 
//


package com.devinotele.smsservice;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeliveryStatistics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeliveryStatistics"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Sent" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Delivered" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Errors" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="InProcess" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Expired" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Rejected" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Optimized" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Tarificated" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="TotalWithErrors" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="DeliveryRatio" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryStatistics", propOrder = {
    "sent",
    "delivered",
    "errors",
    "inProcess",
    "expired",
    "rejected",
    "optimized",
    "tarificated",
    "total",
    "totalWithErrors",
    "deliveryRatio"
})
public class DeliveryStatistics {

    @XmlElement(name = "Sent")
    protected int sent;
    @XmlElement(name = "Delivered")
    protected int delivered;
    @XmlElement(name = "Errors")
    protected int errors;
    @XmlElement(name = "InProcess")
    protected int inProcess;
    @XmlElement(name = "Expired")
    protected int expired;
    @XmlElement(name = "Rejected")
    protected int rejected;
    @XmlElement(name = "Optimized")
    protected int optimized;
    @XmlElement(name = "Tarificated")
    protected int tarificated;
    @XmlElement(name = "Total")
    protected int total;
    @XmlElement(name = "TotalWithErrors")
    protected int totalWithErrors;
    @XmlElement(name = "DeliveryRatio", required = true)
    protected BigDecimal deliveryRatio;

    /**
     * Gets the value of the sent property.
     * 
     */
    public int getSent() {
        return sent;
    }

    /**
     * Sets the value of the sent property.
     * 
     */
    public void setSent(int value) {
        this.sent = value;
    }

    /**
     * Gets the value of the delivered property.
     * 
     */
    public int getDelivered() {
        return delivered;
    }

    /**
     * Sets the value of the delivered property.
     * 
     */
    public void setDelivered(int value) {
        this.delivered = value;
    }

    /**
     * Gets the value of the errors property.
     * 
     */
    public int getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     */
    public void setErrors(int value) {
        this.errors = value;
    }

    /**
     * Gets the value of the inProcess property.
     * 
     */
    public int getInProcess() {
        return inProcess;
    }

    /**
     * Sets the value of the inProcess property.
     * 
     */
    public void setInProcess(int value) {
        this.inProcess = value;
    }

    /**
     * Gets the value of the expired property.
     * 
     */
    public int getExpired() {
        return expired;
    }

    /**
     * Sets the value of the expired property.
     * 
     */
    public void setExpired(int value) {
        this.expired = value;
    }

    /**
     * Gets the value of the rejected property.
     * 
     */
    public int getRejected() {
        return rejected;
    }

    /**
     * Sets the value of the rejected property.
     * 
     */
    public void setRejected(int value) {
        this.rejected = value;
    }

    /**
     * Gets the value of the optimized property.
     * 
     */
    public int getOptimized() {
        return optimized;
    }

    /**
     * Sets the value of the optimized property.
     * 
     */
    public void setOptimized(int value) {
        this.optimized = value;
    }

    /**
     * Gets the value of the tarificated property.
     * 
     */
    public int getTarificated() {
        return tarificated;
    }

    /**
     * Sets the value of the tarificated property.
     * 
     */
    public void setTarificated(int value) {
        this.tarificated = value;
    }

    /**
     * Gets the value of the total property.
     * 
     */
    public int getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     */
    public void setTotal(int value) {
        this.total = value;
    }

    /**
     * Gets the value of the totalWithErrors property.
     * 
     */
    public int getTotalWithErrors() {
        return totalWithErrors;
    }

    /**
     * Sets the value of the totalWithErrors property.
     * 
     */
    public void setTotalWithErrors(int value) {
        this.totalWithErrors = value;
    }

    /**
     * Gets the value of the deliveryRatio property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDeliveryRatio() {
        return deliveryRatio;
    }

    /**
     * Sets the value of the deliveryRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDeliveryRatio(BigDecimal value) {
        this.deliveryRatio = value;
    }

}
