//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.25 at 04:34:25 PM MSK 
//


package com.devinotele.smsservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.devinotele.smsservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.devinotele.smsservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMessageState }
     * 
     */
    public GetMessageState createGetMessageState() {
        return new GetMessageState();
    }

    /**
     * Create an instance of {@link GetMessageStateResponse }
     * 
     */
    public GetMessageStateResponse createGetMessageStateResponse() {
        return new GetMessageStateResponse();
    }

    /**
     * Create an instance of {@link SmsMessageStateInfo }
     * 
     */
    public SmsMessageStateInfo createSmsMessageStateInfo() {
        return new SmsMessageStateInfo();
    }

    /**
     * Create an instance of {@link GetSessionID }
     * 
     */
    public GetSessionID createGetSessionID() {
        return new GetSessionID();
    }

    /**
     * Create an instance of {@link GetSessionIDResponse }
     * 
     */
    public GetSessionIDResponse createGetSessionIDResponse() {
        return new GetSessionIDResponse();
    }

    /**
     * Create an instance of {@link SendMessage }
     * 
     */
    public SendMessage createSendMessage() {
        return new SendMessage();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
    public SendMessageResponse createSendMessageResponse() {
        return new SendMessageResponse();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link SendMessageByTimeZone }
     * 
     */
    public SendMessageByTimeZone createSendMessageByTimeZone() {
        return new SendMessageByTimeZone();
    }

    /**
     * Create an instance of {@link SendMessageByTimeZoneResponse }
     * 
     */
    public SendMessageByTimeZoneResponse createSendMessageByTimeZoneResponse() {
        return new SendMessageByTimeZoneResponse();
    }

    /**
     * Create an instance of {@link SendMessageByTimeZoneToAddresses }
     * 
     */
    public SendMessageByTimeZoneToAddresses createSendMessageByTimeZoneToAddresses() {
        return new SendMessageByTimeZoneToAddresses();
    }

    /**
     * Create an instance of {@link SendMessageByTimeZoneToAddressesResponse }
     * 
     */
    public SendMessageByTimeZoneToAddressesResponse createSendMessageByTimeZoneToAddressesResponse() {
        return new SendMessageByTimeZoneToAddressesResponse();
    }

    /**
     * Create an instance of {@link GetBalance }
     * 
     */
    public GetBalance createGetBalance() {
        return new GetBalance();
    }

    /**
     * Create an instance of {@link GetBalanceResponse }
     * 
     */
    public GetBalanceResponse createGetBalanceResponse() {
        return new GetBalanceResponse();
    }

    /**
     * Create an instance of {@link GetIncomingMessages }
     * 
     */
    public GetIncomingMessages createGetIncomingMessages() {
        return new GetIncomingMessages();
    }

    /**
     * Create an instance of {@link GetIncomingMessagesResponse }
     * 
     */
    public GetIncomingMessagesResponse createGetIncomingMessagesResponse() {
        return new GetIncomingMessagesResponse();
    }

    /**
     * Create an instance of {@link ArrayOfIncomingMessage }
     * 
     */
    public ArrayOfIncomingMessage createArrayOfIncomingMessage() {
        return new ArrayOfIncomingMessage();
    }

    /**
     * Create an instance of {@link GetStatistics }
     * 
     */
    public GetStatistics createGetStatistics() {
        return new GetStatistics();
    }

    /**
     * Create an instance of {@link GetStatisticsResponse }
     * 
     */
    public GetStatisticsResponse createGetStatisticsResponse() {
        return new GetStatisticsResponse();
    }

    /**
     * Create an instance of {@link DeliveryStatistics }
     * 
     */
    public DeliveryStatistics createDeliveryStatistics() {
        return new DeliveryStatistics();
    }

    /**
     * Create an instance of {@link IncomingMessage }
     * 
     */
    public IncomingMessage createIncomingMessage() {
        return new IncomingMessage();
    }

}
